project:
  type: website
  output-dir: docs
  render:
    - purpose_page.qmd
    - intended_user_page.qmd
    - dataset_background_page.qmd
    - data_modeling_page.qmd
    - version_control_page.qmd
    - wrangling_data_page.qmd
    - uploading_page.qmd
    - EML_metadata_page.qmd
    - publishing_page.qmd
    - use_stats_page.qmd
        
format:
  html:
    toc: true

website:
  repo-url: "https://github.com/kylieh10/gomx_sediment_macrofauna"
  sidebar:
    style: "docked"
    background: green
    search: true    
    contents:
      - href: purpose_page.qmd
        text: Why are we doing this?
      - href: intended_user_page.qmd
        text: Intended User
      - href: dataset_background_page.qmd
        text: Dataset Background
      - href: data_modeling_page.qmd
        text: Getting a Feel for the Data
      - href: version_control_page.qmd
        text: Version Control with Git
      - href: wrangling_data_page.qmd
        text: Wrangling the Data
      - href: uploading_page.qmd
        text: Uploading to the IPT
      - href: EML_metadata_page.qmd
        text: Creating EML Metadata
      - href: publishing_page.qmd
        text: Publishing to GBIF and OBIS
      - href: use_stats_page.qmd
        text: Dataset Use Statistics
      
      
      
      
      