project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - purpose_page.qmd
    - intended_user_page.qmd
    - dataset_background_page.qmd
    - data_modeling_page.qmd
    - version_control_page.qmd
    - wrangling_data_page.qmd
    - uploading_page.qmd
    - EML_metadata_page.qmd
    - publishing_page.qmd
    #- use_stats_page.qmd
    - event_core_page.qmd
    - occ_ext_page.qmd
    - eMoF_ext_page.qmd
    - links_page.qmd
    - add_resources_page.qmd
    
format:
  html:
    toc: true
    css: styles.css
    
website:
  title: "An elegant guide to mobilizing data to OBIS & GBIF for the discerning member of the Demopoulos lab."
  navbar: 
    tools:
      - icon: github
        href: "https://github.com/kylieh10/gomx_sediment_macrofauna"
  page-navigation: true
  sidebar:
    style: "docked"
    background: "lightgray"
    search: true
    contents:
      - section: "Background"
        contents: 
          - href: purpose_page.qmd
            text: Why are we doing this?
          - href: intended_user_page.qmd
            text: Intended User
          - href: dataset_background_page.qmd
            text: Dataset Background
      - section: "Working with the Data"
        contents: 
          - href: data_modeling_page.qmd
            text: Getting a Feel for the Data
          - href: version_control_page.qmd
            text: Version Control with Git
          - href: wrangling_data_page.qmd
            text: Wrangling the Data
      - section: "Publication and Reuse"
        contents: 
          - href: publishing_page.qmd
            text: Publishing to GBIF and OBIS
          #- href: use_stats_page.qmd
           # text: Dataset Use Statistics
      - section: "Executable Example Scripts"
        contents: 
          - href: event_core_page.qmd
            text: Event Core Example Script
          - href: occ_ext_page.qmd
            text: Occurrence Extension Example Script
          - href: eMoF_ext_page.qmd
            text: eMoF Extension Example Script
      - section: "Links and Resources"
        contents: 
          - href: links_page.qmd
            text: Links within this Notebook
          - href: add_resources_page.qmd
            text: Additional Resources

      
      
      
      
      